---
- name: Setup MySQL and Apply Migrations
  hosts: localhost
  become: true

  tasks:
    - name: Ensure MySQL is running
      shell: sudo service mysql start

    - name: Create subscriber database using raw SQL
      shell: |
        echo "CREATE DATABASE IF NOT EXISTS subscribers;" | sudo mysql -u root

    - name: Run Flyway migrations
      shell: ./flyway/flyway -configFiles=flyway.conf migrate

